-- @@@@@@ DISCLAIMER: test data was generated by AI and looked over by a human @@@@@@

-- |--- user ---|
INSERT INTO "user" (id, user_name, email, password_hash, creation_date) VALUES
    ('11111111-1111-1111-1111-111111111111', 'alice', 'alice@example.com', '$2a$10$av3XnNBbbmW8dcRcuqi3iOFGIF0l2otw6t0OVXQ0S/sD3ttcC6bNG', '2024-02-15'),
    ('22222222-2222-2222-2222-222222222222', 'bob',   'bob@example.com',   '$2a$10$av3XnNBbbmW8dcRcuqi3iOFGIF0l2otw6t0OVXQ0S/sD3ttcC6bNG',  '2024-05-09'),
    ('33333333-3333-3333-3333-333333333333', 'carol', 'carol@example.com', '$2a$10$av3XnNBbbmW8dcRcuqi3iOFGIF0l2otw6t0OVXQ0S/sD3ttcC6bNG',  '2024-08-23');

-- |--- tag ---|
INSERT INTO tag (id, name, tag_type) VALUES
    ('a1000001-0000-0000-0000-000000000001', 'Science', 'CATEGORY'),
    ('a1000002-0000-0000-0000-000000000002', 'Fantasy', 'CATEGORY'),
    ('a1000003-0000-0000-0000-000000000003', 'Programming', 'CATEGORY'),
    ('a1000004-0000-0000-0000-000000000004', 'Horror', 'CATEGORY'),
    ('a2000005-0000-0000-0000-000000000005', 'For All Ages', 'AGE_GROUP'),
    ('a2000006-0000-0000-0000-000000000006', '18+', 'AGE_GROUP'),
    ('a3000007-0000-0000-0000-000000000007', 'English', 'LANGUAGE'),
    ('a3000008-0000-0000-0000-000000000008', 'German', 'LANGUAGE');

-- |--- book ---|
INSERT INTO book (id, title, description, creation_date, is_public, user_id) VALUES
    ('b0000001-0000-0000-0000-000000000001', 'Clean Code', 'A handbook of agile software craftsmanship.', '2008-08-01', true,  '33333333-3333-3333-3333-333333333333'),
    ('b0000002-0000-0000-0000-000000000002', 'The Science of Interstellar', 'Behind the physics of the film.', '2014-11-07', true, '11111111-1111-1111-1111-111111111111'),
    ('b0000003-0000-0000-0000-000000000003', 'The Green Planet', 'Exploring Earth’s flora.', '2021-04-21', false, '22222222-2222-2222-2222-222222222222'),
    ('b0000004-0000-0000-0000-000000000004', 'Fantasy Realms', 'Short stories from beyond.', '2019-02-13', true, '11111111-1111-1111-1111-111111111111'),
    ('b0000005-0000-0000-0000-000000000005', 'Programming Pearls', 'Essays on programming techniques and problem solving.', '2000-09-01', true, '33333333-3333-3333-3333-333333333333');

-- |--- chapter ---|
INSERT INTO chapter (id, title, text, description, chapter_number, book_id) VALUES
    ('c0000001-0000-0000-0000-000000000001', 'Meaningful Names', 'Long text about naming...', 'Naming matters.', 1, 'b0000001-0000-0000-0000-000000000001'),
    ('c0000002-0000-0000-0000-000000000002', 'Functions', 'On small functions...', 'Small and focused functions.', 2, 'b0000001-0000-0000-0000-000000000001'),
    ('c0000003-0000-0000-0000-000000000003', 'Black Holes', 'Explaining gravity wells...', 'Kerr and Schwarzschild.', 1, 'b0000002-0000-0000-0000-000000000002'),
    ('c0000004-0000-0000-0000-000000000004', 'Wormholes', 'Speculative bridges...', 'Einstein–Rosen bridges.', 2, 'b0000002-0000-0000-0000-000000000002'),
    ('c0000005-0000-0000-0000-000000000005', 'Forests', 'Plant ecosystems...', 'Biodiversity and climate.', 1, 'b0000003-0000-0000-0000-000000000003'),
    ('c0000006-0000-0000-0000-000000000006', 'Elven Cities', 'A tale of light...', 'Myths of old.', 1, 'b0000004-0000-0000-0000-000000000004'),
    ('c0000007-0000-0000-0000-000000000007', 'Orcish Plains', 'Dust and thunder...', 'War drums.', 2, 'b0000004-0000-0000-0000-000000000004'),
    ('c0000008-0000-0000-0000-000000000008', 'Data Structures', 'Arrays, lists, maps...', 'Core building blocks.', 1, 'b0000005-0000-0000-0000-000000000005'),
    ('c0000009-0000-0000-0000-000000000009', 'Algorithmic Thinking', 'Patterns and trade-offs...', 'Complexity and clarity.', 2, 'b0000005-0000-0000-0000-000000000005');

-- |--- book_has_tag (book ↔ tag) ---|
INSERT INTO book_has_tag (book_id, tag_id) VALUES
    ('b0000001-0000-0000-0000-000000000001', 'a1000001-0000-0000-0000-000000000001'),
    ('b0000001-0000-0000-0000-000000000001', 'a1000004-0000-0000-0000-000000000004'),
    ('b0000001-0000-0000-0000-000000000001', 'a3000007-0000-0000-0000-000000000007'),
    ('b0000002-0000-0000-0000-000000000002', 'a1000004-0000-0000-0000-000000000004'),
    ('b0000002-0000-0000-0000-000000000002', 'a2000006-0000-0000-0000-000000000006'),
    ('b0000003-0000-0000-0000-000000000003', 'a1000001-0000-0000-0000-000000000001'),
    ('b0000003-0000-0000-0000-000000000003', 'a3000007-0000-0000-0000-000000000007'),
    ('b0000004-0000-0000-0000-000000000004', 'a3000007-0000-0000-0000-000000000007'),
    ('b0000004-0000-0000-0000-000000000004', 'a1000003-0000-0000-0000-000000000003'),
    ('b0000004-0000-0000-0000-000000000004', 'a1000004-0000-0000-0000-000000000004'),
    ('b0000005-0000-0000-0000-000000000005', 'a2000005-0000-0000-0000-000000000005');

-- |--- user_liked_book (user ↔ liked books) ---|
INSERT INTO user_likes_book (users_id, book_id) VALUES
    ('11111111-1111-1111-1111-111111111111', 'b0000001-0000-0000-0000-000000000001'),
    ('11111111-1111-1111-1111-111111111111', 'b0000004-0000-0000-0000-000000000004'),
    ('22222222-2222-2222-2222-222222222222', 'b0000002-0000-0000-0000-000000000002'),
    ('22222222-2222-2222-2222-222222222222', 'b0000005-0000-0000-0000-000000000005'),
    ('33333333-3333-3333-3333-333333333333', 'b0000003-0000-0000-0000-000000000003');
